CREATE TABLE PUBLISHER (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	ADDRESS VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(100),
	PUBLISHED TIMESTAMP,
	PRICE DECIMAL(18,4),
	PUBLISHER_ID INTEGER,
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK_I18N (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	BOOK_ID INTEGER NOT NULL,
	LANG VARCHAR(10),
	TITLE VARCHAR(100),
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK_BIN (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	HARDCOVER BLOB NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE AUTHOR (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	SECRET VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE AUTHOR_BOOK (
	AUTHOR_ID INTEGER NOT NULL,
	BOOK_ID INTEGER NOT NULL,
	PRIMARY KEY(AUTHOR_ID, BOOK_ID)
);

ALTER TABLE BOOK ADD CONSTRAINT FK_BOOK1 FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID);
ALTER TABLE AUTHOR_BOOK ADD CONSTRAINT FK_AUTHOR_BOOK1 FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID);
ALTER TABLE AUTHOR_BOOK ADD CONSTRAINT FK_AUTHOR_BOOK2 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID);
ALTER TABLE BOOK_BIN ADD CONSTRAINT FK_BOOK_BIN1 FOREIGN KEY (ID) REFERENCES BOOK (ID);
ALTER TABLE BOOK_I18N ADD CONSTRAINT FK_BOOK_I18N1 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID);
ALTER TABLE BOOK_I18N ADD CONSTRAINT UK_BOOK_I18N1 UNIQUE (BOOK_ID, LANG);

CREATE TABLE PROJECT (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	MANAGER_ID INTEGER NOT NULL,
	MANAGER_TYPE CHAR(1) NOT NULL,
	STATUS_COD VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE CONSULTANT (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE EMPLOYEE (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE CATALOG (
	ID INTEGER NOT NULL,
	VERSION INTEGER NOT NULL,
	DOMAIN VARCHAR(10),
	KEY VARCHAR(50),
	"VALUE" VARCHAR(500),
	PRIMARY KEY(ID)
);

CREATE SEQUENCE PUBLISHER_GEN;
CREATE SEQUENCE BOOK_GEN;
CREATE SEQUENCE BOOK_I18N_GEN;
CREATE SEQUENCE BOOK_BIN_GEN;
CREATE SEQUENCE AUTHOR_GEN;
CREATE SEQUENCE PROJECT_GEN;
CREATE SEQUENCE CONSULTANT_GEN;
CREATE SEQUENCE EMPLOYEE_GEN;
CREATE SEQUENCE CATALOG_GEN;

ALTER SEQUENCE PUBLISHER_GEN RESTART WITH 100;
ALTER SEQUENCE BOOK_GEN RESTART WITH 100;
ALTER SEQUENCE BOOK_I18N_GEN RESTART WITH 100;
ALTER SEQUENCE BOOK_BIN_GEN RESTART WITH 100;
ALTER SEQUENCE AUTHOR_GEN RESTART WITH 100;
ALTER SEQUENCE PROJECT_GEN RESTART WITH 100;
ALTER SEQUENCE CONSULTANT_GEN RESTART WITH 100;
ALTER SEQUENCE EMPLOYEE_GEN RESTART WITH 100;
ALTER SEQUENCE CATALOG_GEN RESTART WITH 100;
