CREATE TABLE PUBLISHER (
	ID serial,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	ADDRESS VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK (
	ID serial,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(100),
	PUBLISHED TIMESTAMP,
	PRICE DECIMAL(18,4),
	PUBLISHER_ID BIGINT,
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK_I18N (
	ID serial,
	VERSION INTEGER NOT NULL,
	BOOK_ID BIGINT NOT NULL,
	LANG VARCHAR(10),
	TITLE VARCHAR(100),
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK_BIN (
	ID serial,
	VERSION INTEGER NOT NULL,
	HARDCOVER bytea NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE AUTHOR (
	ID serial,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE AUTHOR_BOOK (
	AUTHOR_ID BIGINT NOT NULL,
	BOOK_ID BIGINT NOT NULL,
	PRIMARY KEY(AUTHOR_ID, BOOK_ID)
);

ALTER TABLE BOOK ADD CONSTRAINT FK_BOOK1 FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID);
ALTER TABLE AUTHOR_BOOK ADD CONSTRAINT FK_AUTHOR_BOOK1 FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID);
ALTER TABLE AUTHOR_BOOK ADD CONSTRAINT FK_AUTHOR_BOOK2 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID);
ALTER TABLE BOOK_BIN ADD CONSTRAINT FK_BOOK_BIN1 FOREIGN KEY (ID) REFERENCES BOOK (ID);
ALTER TABLE BOOK_I18N ADD CONSTRAINT FK_BOOK_I18N1 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID);
ALTER TABLE BOOK_I18N ADD CONSTRAINT UK_BOOK_I18N1 UNIQUE (BOOK_ID, LANG);

CREATE TABLE PROJECT (
	ID serial,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	MANAGER_ID BIGINT NOT NULL,
	MANAGER_TYPE CHAR(1) NOT NULL,
	STATUS_COD VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE CONSULTANT (
	ID serial,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE EMPLOYEE (
	ID serial,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(50),
	PRIMARY KEY(ID)
);

CREATE TABLE CATALOG (
	ID serial,
	VERSION INTEGER NOT NULL,
	DOMAIN VARCHAR(10),
	KEY VARCHAR(50),
	VALUE VARCHAR(500),
	PRIMARY KEY(ID)
);
