CREATE TABLE `PUBLISHER` (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VERSION INTEGER NOT NULL,
	`NAME` VARCHAR(50),
	`ADDRESS` VARCHAR(255),
	PRIMARY KEY(ID)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `BOOK` (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VERSION INTEGER NOT NULL,
	`NAME` VARCHAR(100),
	`PUBLISHED` TIMESTAMP,
	`PUBLISHER_ID` BIGINT,
	PRIMARY KEY(ID)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `BOOK_BIN` (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VERSION INTEGER NOT NULL,
	`HARDCOVER` LONGBLOB NOT NULL,
	PRIMARY KEY(ID)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHOR` (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VERSION INTEGER NOT NULL,
	`NAME` VARCHAR(50),
	PRIMARY KEY(ID)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHOR_BOOK` (
	AUTHOR_ID BIGINT NOT NULL,
	BOOK_ID BIGINT NOT NULL,
	PRIMARY KEY(AUTHOR_ID, BOOK_ID)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

ALTER TABLE `BOOK` ADD CONSTRAINT FK_BOOK1 FOREIGN KEY (`PUBLISHER_ID`) REFERENCES `PUBLISHER` (ID);
ALTER TABLE `AUTHOR_BOOK` ADD CONSTRAINT FK_AUTHOR_BOOK1 FOREIGN KEY (`AUTHOR_ID`) REFERENCES `AUTHOR` (ID);
ALTER TABLE `AUTHOR_BOOK` ADD CONSTRAINT FK_AUTHOR_BOOK2 FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (ID);
ALTER TABLE `BOOK_BIN` ADD CONSTRAINT FK_BOOK_BIN1 FOREIGN KEY (`ID`) REFERENCES `BOOK` (`ID`);
